void swap(void *[], int, int);
void myqsort(void *[], int, int, int (*)(void *, void *));
void selectinsort(char *[], int);
void insertionsort(char *[], int);
void bubblesort(char *[],int);
void shellsort(char *[],int);
void merge(char *[],int,int,int);
void mergesort(char *[],int, int);
void heapify(char *[], int);
void heapsort(char *[], int);
